### ISSUE TITLE
Getting "Maximum call stack exceeded" error

### ISSUE THREAD

**Issue by gwynjudd** [jonchardy/typedoc-plugin-no-inherit#6]
Getting this error when trying to run using this plugin. I didn't add any `@noInheritDocs` yet. If I remove the plugin, the error goes away.

```
λ npm run docs

> touch-core@13.1.0 docs C:\Users\gjudd\Develop\Mobility\Develop\Touch\Touch\core
> npx rimraf documentation && npx typedoc --name "StayinFront Touch Core" --readme none --ignoreCompilerErrors --out documentation/ app/

Loaded plugin C:\Users\gjudd\Develop\Mobility\Develop\Touch\Touch\core\node_modules\typedoc-plugin-external-module-name
Loaded plugin C:\Users\gjudd\Develop\Mobility\Develop\Touch\Touch\core\node_modules\typedoc-plugin-internal-external
Loaded plugin C:\Users\gjudd\Develop\Mobility\Develop\Touch\Touch\core\node_modules\typedoc-plugin-no-inherit

Using TypeScript 3.2.4 from C:\Users\gjudd\Develop\Mobility\Develop\Touch\Touch\core\node_modules\typedoc\node_modules\typescript\lib
Maximum call stack size exceeded
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! touch-core@13.1.0 docs: `npx rimraf documentation && npx typedoc --name "StayinFront Touch Core" --readme none --ignoreCompilerErrors --out documentation/ app/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the touch-core@13.1.0 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gjudd\AppData\Roaming\npm-cache\_logs\2019-01-31T04_01_22_148Z-debug.log
```                                                     

Any ideas?

**Comment by jonchardy** [comment]
Odd. Do you have a really long inheritance chain somewhere in your code? Because of the way typedoc reflection removal is structured, the plugin has to mark any reflection that is inherited from somewhere else, then go up the hierarchy to see if any of the parents are marked as noInheritDoc to see if it needs removal.

Maybe you can add some output statements to the plugin in `isNoInheritUpHierarchy` to see why it's exceeding the call stack.

```js
this.application.logger.write(...);
```

Ideally, this could be done after the chain was resolved, since it could be done top-down, but unfortunately that's not currently the case.

**Comment by gwynjudd** [comment]
Yes I suspect that is certainly the case. Our code base is pretty large and has a reasonable amount of inheritance going on. Particularly using declaration files for things like Marionette and Backbone which tend to bloat it out. I don't really know how long the chain can get, or how to tell really.

happy to try stuff out, can you give me some specific statements you want me to add?

**Comment by jonchardy** [comment]
I just published a change that will stop on inheritance chains of 20+ (which seems excessive) and output a warning. It should show you the top level reflections being inherited, that way you can add @noInheritDoc where needed. Let me know how if it helps resolve your issue.

**Comment by dtysky** [comment]
Still not working, in line 114 of dist/plugin:

```js
this.application.logger.warn(`Found inheritance chain with depth > 20, stopping no inherit check: ${end.getFullName()}`);
```

It will throw exception:  

>TypeError: Cannot read property 'getFullName' of undefined

I think `{end && end.getFullName()}` will resolve this problem.

Thank.

@jonchardy

**Comment by gwynjudd** [comment]
This patch (https://github.com/jonchardy/typedoc-plugin-no-inherit/commit/e24077572dde57394178b07e11ae8327c97b42a7 and https://github.com/jonchardy/typedoc-plugin-no-inherit/commit/16281f9ee8a34771f17800eee368d582ec81c0c3) seemed to get me closer to the problem.

I did find some unexpected behaviour. The warning "Warning: Found inheritance chain with depth > 20, stopping no inherit check: dropdown.BaseOptions.title" was coming on something that seemed completely benign. Perhaps there is a valid reason for it, but I couldn't really figure out what was going on.

In any case, it doesn't seem like there is anything like 20 levels of inheritance in the area that was causing the issue. To simplify, I have removed all of the things that didn't seem to be related to the issue.

```
export interface ButtonOptions extends Dropdown.Options {

}

export interface Options extends BaseOptions { /// <<<<<<----- Dropdown.Options above

}

export interface BaseOptions {

	title?: string;  /// <<<<<------- the warning occurs on this line
}

export class PageModel extends ItemModel {
	get title(): string { /// <<<<<----- but somehow this appears in the inheritance chain, it is not related in any way to BaseOptions or the other classes above
		return this.get('title');
	}
}

```

I added this warning into the plugin:

```
    isNoInheritUpHierarchy(context, current, end, depth) {
        this.application.logger.warn(`Examining inheritance: ${current && current.getFullName()} - (${ depth })`);
        
        if (depth > 20) {
            this.application.logger.warn(`Found inheritance chain with depth > 20, stopping no inherit check: ${end && end.getFullName()}`);
            return false; // stop if we've recursed more than 20 times
        }
```

And here is the output from the log:

```
Warning: Examining inheritance: search.ButtonOptions.title - (0)
Warning: Examining inheritance: page.PageModel.title - (1)
Warning: Examining inheritance: page.PageModel.title - (2)
Warning: Examining inheritance: page.PageModel.title - (3)
Warning: Examining inheritance: page.PageModel.title - (4)
Warning: Examining inheritance: page.PageModel.title - (5)
Warning: Examining inheritance: page.PageModel.title - (6)
Warning: Examining inheritance: page.PageModel.title - (7)
Warning: Examining inheritance: page.PageModel.title - (8)
Warning: Examining inheritance: page.PageModel.title - (9)
Warning: Examining inheritance: page.PageModel.title - (10)
Warning: Examining inheritance: page.PageModel.title - (11)
Warning: Examining inheritance: page.PageModel.title - (12)
Warning: Examining inheritance: page.PageModel.title - (13)
Warning: Examining inheritance: page.PageModel.title - (14)
Warning: Examining inheritance: page.PageModel.title - (15)
Warning: Examining inheritance: page.PageModel.title - (16)
Warning: Examining inheritance: page.PageModel.title - (17)
Warning: Examining inheritance: page.PageModel.title - (18)
Warning: Examining inheritance: page.PageModel.title - (19)
Warning: Examining inheritance: page.PageModel.title - (20)
Warning: Examining inheritance: page.PageModel.title - (21)
```

I don't really understand it.

**Comment by jonchardy** [comment]
The undefined issue should be resolved. I'll see if I can figure out what's going on with the weird inheritance chain.

**Comment by jonchardy** [comment]
I just tried adding your classes/interfaces from above in a test file, and I'm not getting any issues. The only thing I can think of is that resolveType is finding the wrong parent reflection somehow. Maybe you can try adding some messages before the return statements there to figure out which return is happening and what it's returning.

**Comment by gwynjudd** [comment]
@jonchardy I did some looking into it and made a minimal example here:

https://github.com/gwynjudd/type

To replicate the issue:

1. checkout the repo above
2. npm install
3. npm run docs

```
C:\Users\gjudd\Develop\github\type [master]
λ npm run docs

> type@1.0.0 docs C:\Users\gjudd\Develop\github\type
> npx typedoc --options tools/typedoc.js

Loaded plugin C:\Users\gjudd\Develop\github\type\node_modules\typedoc-plugin-no-inherit

Using TypeScript 3.2.4 from C:\Users\gjudd\Develop\github\type\node_modules\typedoc\node_modules\typescript\lib
Warning: Found inheritance chain with depth > 20, stopping no inherit check: "d".ID.title
Rendering [========================================] 100%

Documentation generated at C:\Users\gjudd\Develop\github\type\documentation
```

If you do "npm uninstall typedoc-plugin-no-inherit", the warning doesn't occur.

In my minimal example, the problem occurs when documenting the "title" field in "IB". It goes up the first inheritance chain through "IC", doesn't find it, goes up again to the module "b", doesn't find it, goes up again to the "test" project and eventually finds a "title" in the unrelated "IA".

It then goes into an infinite loop looking for it in "IA".

**Comment by jonchardy** [comment]
I see. I've updated the code to use getChildByName, which will only search the given reflection for a child. If you get 1.1.6, the issue should be resolved. Thanks for all your help and the reproducible case.

**Comment by gwynjudd** [comment]
@jonchardy yes looks good thanks
